// Table configuration for nemtor_units table
export const tableConfig = {
  columns: [
    { field: 'unit_id', header: 'Unit ID', width: 100 },
    { field: 'fk_gcon_piece_id', header: 'GCon Piece ID', width: 100 },
    { field: 'unit_marker', header: 'Unit Marker', width: 120 },
    { field: 'el_id', header: 'Element ID', width: 100 },
    { field: 'el_type', header: 'Element Type', width: 100 },
    { field: 'widget_type', header: 'Widget Type', width: 120 },
    { field: 'parent_el_id', header: 'Parent Element ID', width: 120 },
    { field: 'position_order', header: 'Position Order', width: 80 },
    { field: 'depth_level', header: 'Depth Level', width: 80 },
    { field: 'sort_index', header: 'Sort Index', width: 80 },
    { field: 'summary_text', header: 'Summary Text', width: 200 },
    { field: 'unit_label', header: 'Unit Label', width: 150 },
    { field: 'settings_json', header: 'Settings JSON', width: 150, format: (value: any) => value ? JSON.stringify(value).slice(0, 50) + '...' : '' },
    { field: 'style_json', header: 'Style JSON', width: 150, format: (value: any) => value ? JSON.stringify(value).slice(0, 50) + '...' : '' },
    { field: 'globals_json', header: 'Globals JSON', width: 150, format: (value: any) => value ? JSON.stringify(value).slice(0, 50) + '...' : '' },
    { field: 'raw_json', header: 'Raw JSON', width: 150, format: (value: any) => value ? JSON.stringify(value).slice(0, 50) + '...' : '' },
    { field: 'created_at', header: 'Created At', width: 150, format: (value: any) => value ? new Date(value).toLocaleString() : '' },
    { field: 'updated_at', header: 'Updated At', width: 150, format: (value: any) => value ? new Date(value).toLocaleString() : '' },
    { field: 'full_text_cached', header: 'Full Text Cached', width: 200 },
    { field: 'full_text_edits', header: 'Full Text Edits', width: 200 },
    { field: 'image_type', header: 'Image Type', width: 100 },
    { field: 'image_id', header: 'Image ID', width: 100 },
    { field: 'image_url', header: 'Image URL', width: 200 },
    { field: 'image_alt', header: 'Image Alt', width: 150 },
    { field: 'image_size', header: 'Image Size', width: 100 },
    { field: 'image_source', header: 'Image Source', width: 120 },
    { field: 'carousel_position', header: 'Carousel Position', width: 80 },
    { field: 'image_context', header: 'Image Context', width: 150 },
    { field: 'has_img_slot', header: 'Has Image Slot', width: 80, format: (value: any) => value ? 'Yes' : 'No' },
    { field: 'img_slot_qty', header: 'Image Slot Qty', width: 80 },
    { field: 'tar_description_text', header: 'TAR Description Text', width: 200 },
    { field: 'tar_description_text_edits', header: 'TAR Description Edits', width: 200 }
  ],
  headerRows: [
    [
      { text: 'Unit ID', colSpan: 1 },
      { text: 'GCon Piece ID', colSpan: 1 },
      { text: 'Unit Marker', colSpan: 1 },
      { text: 'Element ID', colSpan: 1 },
      { text: 'Element Type', colSpan: 1 },
      { text: 'Widget Type', colSpan: 1 },
      { text: 'Parent Element ID', colSpan: 1 },
      { text: 'Position Order', colSpan: 1 },
      { text: 'Depth Level', colSpan: 1 },
      { text: 'Sort Index', colSpan: 1 },
      { text: 'Summary Text', colSpan: 1 },
      { text: 'Unit Label', colSpan: 1 },
      { text: 'Settings JSON', colSpan: 1 },
      { text: 'Style JSON', colSpan: 1 },
      { text: 'Globals JSON', colSpan: 1 },
      { text: 'Raw JSON', colSpan: 1 },
      { text: 'Created At', colSpan: 1 },
      { text: 'Updated At', colSpan: 1 },
      { text: 'Full Text Cached', colSpan: 1 },
      { text: 'Full Text Edits', colSpan: 1 },
      { text: 'Image Type', colSpan: 1 },
      { text: 'Image ID', colSpan: 1 },
      { text: 'Image URL', colSpan: 1 },
      { text: 'Image Alt', colSpan: 1 },
      { text: 'Image Size', colSpan: 1 },
      { text: 'Image Source', colSpan: 1 },
      { text: 'Carousel Position', colSpan: 1 },
      { text: 'Image Context', colSpan: 1 },
      { text: 'Has Image Slot', colSpan: 1 },
      { text: 'Image Slot Qty', colSpan: 1 },
      { text: 'TAR Description Text', colSpan: 1 },
      { text: 'TAR Description Edits', colSpan: 1 }
    ]
  ]
};