import { IconRegistryEntry } from './types/iconTypes';

export const EXPANDED_ICON_REGISTRY: IconRegistryEntry[] = [
  // Basic Shapes (15)
  { iconName: 'circle', displayName: 'Circle', category: 'shapes', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'square', displayName: 'Square', category: 'shapes', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'triangle', displayName: 'Triangle', category: 'shapes', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'star', displayName: 'Star', category: 'shapes', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'heart', displayName: 'Heart', category: 'shapes', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'diamond', displayName: 'Diamond', category: 'shapes', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'hexagon', displayName: 'Hexagon', category: 'shapes', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'pentagon', displayName: 'Pentagon', category: 'shapes', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'octagon', displayName: 'Octagon', category: 'shapes', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'rounded-rect', displayName: 'Rounded Rectangle', category: 'shapes', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'ellipsis', displayName: 'Ellipsis', category: 'shapes', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'infinity', displayName: 'Infinity', category: 'shapes', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'hash', displayName: 'Hash', category: 'shapes', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'at-sign', displayName: 'At Sign', category: 'shapes', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'percent', displayName: 'Percent', category: 'shapes', usageContexts: ['column_templates', 'sites', 'xpages'] },

  // Arrows & Navigation (40)
  { iconName: 'arrow-up', displayName: 'Arrow Up', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'arrow-down', displayName: 'Arrow Down', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'arrow-left', displayName: 'Arrow Left', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'arrow-right', displayName: 'Arrow Right', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'arrow-up-down', displayName: 'Arrow Up Down', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'arrow-left-right', displayName: 'Arrow Left Right', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'arrow-up-left', displayName: 'Arrow Up Left', category: 'arrows', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'arrow-up-right', displayName: 'Arrow Up Right', category: 'arrows', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'arrow-down-left', displayName: 'Arrow Down Left', category: 'arrows', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'arrow-down-right', displayName: 'Arrow Down Right', category: 'arrows', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'chevron-up', displayName: 'Chevron Up', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'chevron-down', displayName: 'Chevron Down', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'chevron-left', displayName: 'Chevron Left', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'chevron-right', displayName: 'Chevron Right', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'chevrons-up', displayName: 'Chevrons Up', category: 'arrows', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'chevrons-down', displayName: 'Chevrons Down', category: 'arrows', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'chevrons-left', displayName: 'Chevrons Left', category: 'arrows', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'chevrons-right', displayName: 'Chevrons Right', category: 'arrows', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'move-up', displayName: 'Move Up', category: 'arrows', usageContexts: ['column_templates', 'xpages'] },
  { iconName: 'move-down', displayName: 'Move Down', category: 'arrows', usageContexts: ['column_templates', 'xpages'] },
  { iconName: 'move-left', displayName: 'Move Left', category: 'arrows', usageContexts: ['column_templates', 'xpages'] },
  { iconName: 'move-right', displayName: 'Move Right', category: 'arrows', usageContexts: ['column_templates', 'xpages'] },
  { iconName: 'move', displayName: 'Move', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'move-3d', displayName: 'Move 3D', category: 'arrows', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'rotate-cw', displayName: 'Rotate Clockwise', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'rotate-ccw', displayName: 'Rotate Counter-Clockwise', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'navigation', displayName: 'Navigation', category: 'arrows', usageContexts: ['sites', 'xpages'] },
  { iconName: 'navigation-2', displayName: 'Navigation 2', category: 'arrows', usageContexts: ['sites', 'xpages'] },
  { iconName: 'map-pin', displayName: 'Map Pin', category: 'arrows', usageContexts: ['sites', 'xpages'] },
  { iconName: 'map', displayName: 'Map', category: 'arrows', usageContexts: ['sites', 'xpages'] },
  { iconName: 'compass', displayName: 'Compass', category: 'arrows', usageContexts: ['sites', 'xpages'] },
  { iconName: 'route', displayName: 'Route', category: 'arrows', usageContexts: ['sites', 'xpages'] },
  { iconName: 'signpost', displayName: 'Signpost', category: 'arrows', usageContexts: ['sites', 'xpages'] },
  { iconName: 'trending-up', displayName: 'Trending Up', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'trending-down', displayName: 'Trending Down', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'corner-up-left', displayName: 'Corner Up Left', category: 'arrows', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'corner-up-right', displayName: 'Corner Up Right', category: 'arrows', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'corner-down-left', displayName: 'Corner Down Left', category: 'arrows', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'corner-down-right', displayName: 'Corner Down Right', category: 'arrows', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'arrow-big-up', displayName: 'Big Arrow Up', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'arrow-big-down', displayName: 'Big Arrow Down', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'arrow-big-left', displayName: 'Big Arrow Left', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'arrow-big-right', displayName: 'Big Arrow Right', category: 'arrows', usageContexts: ['column_templates', 'sites', 'xpages'] },

  // Actions & Controls (50)
  { iconName: 'play', displayName: 'Play', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'pause', displayName: 'Pause', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'stop', displayName: 'Stop', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'skip-forward', displayName: 'Skip Forward', category: 'actions', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'skip-back', displayName: 'Skip Back', category: 'actions', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'fast-forward', displayName: 'Fast Forward', category: 'actions', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'rewind', displayName: 'Rewind', category: 'actions', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'edit', displayName: 'Edit', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'edit-2', displayName: 'Edit 2', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'edit-3', displayName: 'Edit 3', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'pen', displayName: 'Pen', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'pen-tool', displayName: 'Pen Tool', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'pencil', displayName: 'Pencil', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'eraser', displayName: 'Eraser', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'copy', displayName: 'Copy', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'cut', displayName: 'Cut', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'paste', displayName: 'Paste', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'clipboard', displayName: 'Clipboard', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'clipboard-copy', displayName: 'Clipboard Copy', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'clipboard-paste', displayName: 'Clipboard Paste', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'clipboard-check', displayName: 'Clipboard Check', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'save', displayName: 'Save', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'download', displayName: 'Download', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'upload', displayName: 'Upload', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'share', displayName: 'Share', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'share-2', displayName: 'Share 2', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'send', displayName: 'Send', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'send-horizontal', displayName: 'Send Horizontal', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'search', displayName: 'Search', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'filter', displayName: 'Filter', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'filter-x', displayName: 'Filter X', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'shuffle', displayName: 'Shuffle', category: 'actions', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'repeat', displayName: 'Repeat', category: 'actions', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'repeat-1', displayName: 'Repeat 1', category: 'actions', usageContexts: ['column_templates', 'sites'] },
  { iconName: 'undo', displayName: 'Undo', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'redo', displayName: 'Redo', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'refresh-cw', displayName: 'Refresh Clockwise', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'refresh-ccw', displayName: 'Refresh Counter-Clockwise', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'plus', displayName: 'Plus', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'minus', displayName: 'Minus', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'x', displayName: 'X', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'check', displayName: 'Check', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'check-check', displayName: 'Check Check', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'x-circle', displayName: 'X Circle', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'check-circle', displayName: 'Check Circle', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'more-horizontal', displayName: 'More Horizontal', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'more-vertical', displayName: 'More Vertical', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'menu', displayName: 'Menu', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'grid-3x3', displayName: 'Grid 3x3', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'list', displayName: 'List', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'settings', displayName: 'Settings', category: 'actions', usageContexts: ['column_templates', 'sites', 'xpages'] },

  // Status & Alerts (30)
  { iconName: 'alert-circle', displayName: 'Alert Circle', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'alert-triangle', displayName: 'Alert Triangle', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'alert-octagon', displayName: 'Alert Octagon', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'info', displayName: 'Info', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'help-circle', displayName: 'Help Circle', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'check-circle-2', displayName: 'Check Circle 2', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'clock', displayName: 'Clock', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'timer', displayName: 'Timer', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'hourglass', displayName: 'Hourglass', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'shield', displayName: 'Shield', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'shield-check', displayName: 'Shield Check', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'shield-alert', displayName: 'Shield Alert', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'shield-x', displayName: 'Shield X', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'lock', displayName: 'Lock', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'unlock', displayName: 'Unlock', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'eye', displayName: 'Eye', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'eye-off', displayName: 'Eye Off', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'bell', displayName: 'Bell', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'bell-off', displayName: 'Bell Off', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'bell-ring', displayName: 'Bell Ring', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'zap', displayName: 'Zap', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'zap-off', displayName: 'Zap Off', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'power', displayName: 'Power', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'power-off', displayName: 'Power Off', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'loader', displayName: 'Loader', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'loader-2', displayName: 'Loader 2', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'circle-dot', displayName: 'Circle Dot', category: 'status', usageContexts: ['column_templates', 'sites', 'xpages'] },

  // Files & Documents (35)
  { iconName: 'file', displayName: 'File', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'file-text', displayName: 'File Text', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'file-image', displayName: 'File Image', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'file-video', displayName: 'File Video', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'file-audio', displayName: 'File Audio', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'folder', displayName: 'Folder', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'folder-open', displayName: 'Folder Open', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'folder-plus', displayName: 'Folder Plus', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'folder-minus', displayName: 'Folder Minus', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'folder-x', displayName: 'Folder X', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'file-edit', displayName: 'File Edit', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'file-plus', displayName: 'File Plus', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'file-minus', displayName: 'File Minus', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'file-x', displayName: 'File X', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'file-check', displayName: 'File Check', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'paperclip', displayName: 'Paperclip', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'link', displayName: 'Link', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'link-2', displayName: 'Link 2', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'unlink', displayName: 'Unlink', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'archive', displayName: 'Archive', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'package', displayName: 'Package', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'book', displayName: 'Book', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'book-open', displayName: 'Book Open', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'bookmark', displayName: 'Bookmark', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'bookmark-plus', displayName: 'Bookmark Plus', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'newspaper', displayName: 'Newspaper', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'notebook', displayName: 'Notebook', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'notebook-pen', displayName: 'Notebook Pen', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'sticky-note', displayName: 'Sticky Note', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'database', displayName: 'Database', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'server', displayName: 'Server', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'hard-drive', displayName: 'Hard Drive', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'usb', displayName: 'USB', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'disc', displayName: 'Disc', category: 'files', usageContexts: ['column_templates', 'sites', 'xpages'] },

  // Communication (25)
  { iconName: 'mail', displayName: 'Mail', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'mail-open', displayName: 'Mail Open', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'mail-plus', displayName: 'Mail Plus', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'mail-minus', displayName: 'Mail Minus', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'mail-x', displayName: 'Mail X', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'mail-check', displayName: 'Mail Check', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'message-circle', displayName: 'Message Circle', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'message-square', displayName: 'Message Square', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'message-square-plus', displayName: 'Message Square Plus', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'phone', displayName: 'Phone', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'phone-call', displayName: 'Phone Call', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'phone-incoming', displayName: 'Phone Incoming', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'phone-outgoing', displayName: 'Phone Outgoing', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'phone-off', displayName: 'Phone Off', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'headphones', displayName: 'Headphones', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'mic', displayName: 'Microphone', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'mic-off', displayName: 'Microphone Off', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'volume', displayName: 'Volume', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'volume-1', displayName: 'Volume 1', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'volume-2', displayName: 'Volume 2', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'volume-x', displayName: 'Volume X', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'wifi', displayName: 'WiFi', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'wifi-off', displayName: 'WiFi Off', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'bluetooth', displayName: 'Bluetooth', category: 'communication', usageContexts: ['column_templates', 'sites', 'xpages'] },

  // Technology & Devices (30)
  { iconName: 'laptop', displayName: 'Laptop', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'monitor', displayName: 'Monitor', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'smartphone', displayName: 'Smartphone', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'tablet', displayName: 'Tablet', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'computer', displayName: 'Computer', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'tv', displayName: 'TV', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'camera', displayName: 'Camera', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'video', displayName: 'Video', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'video-off', displayName: 'Video Off', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'image', displayName: 'Image', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'images', displayName: 'Images', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'scan', displayName: 'Scan', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'printer', displayName: 'Printer', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'mouse', displayName: 'Mouse', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'keyboard', displayName: 'Keyboard', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'gamepad-2', displayName: 'Gamepad', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'router', displayName: 'Router', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'cloud', displayName: 'Cloud', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'cloud-upload', displayName: 'Cloud Upload', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'cloud-download', displayName: 'Cloud Download', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'battery', displayName: 'Battery', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'battery-low', displayName: 'Battery Low', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'plug', displayName: 'Plug', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'cable', displayName: 'Cable', category: 'technology', usageContexts: ['column_templates', 'sites', 'xpages'] },

  // User & People (20)
  { iconName: 'user', displayName: 'User', category: 'people', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'users', displayName: 'Users', category: 'people', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'user-plus', displayName: 'User Plus', category: 'people', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'user-minus', displayName: 'User Minus', category: 'people', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'user-x', displayName: 'User X', category: 'people', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'user-check', displayName: 'User Check', category: 'people', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'contact', displayName: 'Contact', category: 'people', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'contacts', displayName: 'Contacts', category: 'people', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'users-2', displayName: 'Users 2', category: 'people', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'crown', displayName: 'Crown', category: 'people', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'user-circle', displayName: 'User Circle', category: 'people', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'user-square', displayName: 'User Square', category: 'people', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'badge-check', displayName: 'Badge Check', category: 'people', usageContexts: ['column_templates', 'sites', 'xpages'] },

  // Business & Finance (25)
  { iconName: 'briefcase', displayName: 'Briefcase', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'building', displayName: 'Building', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'building-2', displayName: 'Building 2', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'store', displayName: 'Store', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'shopping-cart', displayName: 'Shopping Cart', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'shopping-bag', displayName: 'Shopping Bag', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'credit-card', displayName: 'Credit Card', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'banknote', displayName: 'Banknote', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'coins', displayName: 'Coins', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'dollar-sign', displayName: 'Dollar Sign', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'euro', displayName: 'Euro', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'pound-sterling', displayName: 'Pound Sterling', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'receipt', displayName: 'Receipt', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'calculator', displayName: 'Calculator', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'pie-chart', displayName: 'Pie Chart', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'bar-chart', displayName: 'Bar Chart', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'line-chart', displayName: 'Line Chart', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'target', displayName: 'Target', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'award', displayName: 'Award', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'trophy', displayName: 'Trophy', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'medal', displayName: 'Medal', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'gift', displayName: 'Gift', category: 'business', usageContexts: ['column_templates', 'sites', 'xpages'] },

  // Transport & Travel (20)
  { iconName: 'car', displayName: 'Car', category: 'transport', usageContexts: ['sites', 'xpages'] },
  { iconName: 'truck', displayName: 'Truck', category: 'transport', usageContexts: ['sites', 'xpages'] },
  { iconName: 'bus', displayName: 'Bus', category: 'transport', usageContexts: ['sites', 'xpages'] },
  { iconName: 'plane', displayName: 'Plane', category: 'transport', usageContexts: ['sites', 'xpages'] },
  { iconName: 'train', displayName: 'Train', category: 'transport', usageContexts: ['sites', 'xpages'] },
  { iconName: 'ship', displayName: 'Ship', category: 'transport', usageContexts: ['sites', 'xpages'] },
  { iconName: 'bike', displayName: 'Bike', category: 'transport', usageContexts: ['sites', 'xpages'] },
  { iconName: 'fuel', displayName: 'Fuel', category: 'transport', usageContexts: ['sites', 'xpages'] },
  { iconName: 'luggage', displayName: 'Luggage', category: 'transport', usageContexts: ['sites', 'xpages'] },
  { iconName: 'backpack', displayName: 'Backpack', category: 'transport', usageContexts: ['sites', 'xpages'] },
  { iconName: 'tent', displayName: 'Tent', category: 'transport', usageContexts: ['sites', 'xpages'] },
  { iconName: 'mountain', displayName: 'Mountain', category: 'transport', usageContexts: ['sites', 'xpages'] },
  { iconName: 'tree-pine', displayName: 'Pine Tree', category: 'transport', usageContexts: ['sites', 'xpages'] },
  { iconName: 'waves', displayName: 'Waves', category: 'transport', usageContexts: ['sites', 'xpages'] },

  // Home & Living (25)
  { iconName: 'home', displayName: 'Home', category: 'home', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'door', displayName: 'Door', category: 'home', usageContexts: ['sites', 'xpages'] },
  { iconName: 'door-open', displayName: 'Door Open', category: 'home', usageContexts: ['sites', 'xpages'] },
  { iconName: 'door-closed', displayName: 'Door Closed', category: 'home', usageContexts: ['sites', 'xpages'] },
  { iconName: 'key', displayName: 'Key', category: 'home', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'bed', displayName: 'Bed', category: 'home', usageContexts: ['sites', 'xpages'] },
  { iconName: 'chair', displayName: 'Chair', category: 'home', usageContexts: ['sites', 'xpages'] },
  { iconName: 'armchair', displayName: 'Armchair', category: 'home', usageContexts: ['sites', 'xpages'] },
  { iconName: 'lamp', displayName: 'Lamp', category: 'home', usageContexts: ['sites', 'xpages'] },
  { iconName: 'lamp-desk', displayName: 'Desk Lamp', category: 'home', usageContexts: ['sites', 'xpages'] },
  { iconName: 'lightbulb', displayName: 'Lightbulb', category: 'home', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'coffee', displayName: 'Coffee', category: 'home', usageContexts: ['sites', 'xpages'] },
  { iconName: 'cup', displayName: 'Cup', category: 'home', usageContexts: ['sites', 'xpages'] },
  { iconName: 'utensils', displayName: 'Utensils', category: 'home', usageContexts: ['sites', 'xpages'] },
  { iconName: 'flower', displayName: 'Flower', category: 'home', usageContexts: ['sites', 'xpages'] },
  { iconName: 'sun', displayName: 'Sun', category: 'home', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'moon', displayName: 'Moon', category: 'home', usageContexts: ['column_templates', 'sites', 'xpages'] },

  // Tools & Objects (30)
  { iconName: 'wrench', displayName: 'Wrench', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'hammer', displayName: 'Hammer', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'screwdriver', displayName: 'Screwdriver', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'scissors', displayName: 'Scissors', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'paint-bucket', displayName: 'Paint Bucket', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'brush', displayName: 'Brush', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'palette', displayName: 'Palette', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'pipette', displayName: 'Pipette', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'magnet', displayName: 'Magnet', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'microscope', displayName: 'Microscope', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'telescope', displayName: 'Telescope', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'glasses', displayName: 'Glasses', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'watch', displayName: 'Watch', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'calendar', displayName: 'Calendar', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'calendar-days', displayName: 'Calendar Days', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'alarm-clock', displayName: 'Alarm Clock', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'trash', displayName: 'Trash', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'trash-2', displayName: 'Trash 2', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'recycle', displayName: 'Recycle', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'boxes', displayName: 'Boxes', category: 'tools', usageContexts: ['column_templates', 'sites', 'xpages'] },

  // Science & Education (20)
  { iconName: 'graduation-cap', displayName: 'Graduation Cap', category: 'education', usageContexts: ['sites', 'xpages'] },
  { iconName: 'school', displayName: 'School', category: 'education', usageContexts: ['sites', 'xpages'] },
  { iconName: 'test-tube', displayName: 'Test Tube', category: 'education', usageContexts: ['sites', 'xpages'] },
  { iconName: 'atom', displayName: 'Atom', category: 'education', usageContexts: ['sites', 'xpages'] },
  { iconName: 'dna', displayName: 'DNA', category: 'education', usageContexts: ['sites', 'xpages'] },
  { iconName: 'beaker', displayName: 'Beaker', category: 'education', usageContexts: ['sites', 'xpages'] },
  { iconName: 'flask-conical', displayName: 'Flask Conical', category: 'education', usageContexts: ['sites', 'xpages'] },
  { iconName: 'globe', displayName: 'Globe', category: 'education', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'earth', displayName: 'Earth', category: 'education', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'flame', displayName: 'Flame', category: 'education', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'thermometer', displayName: 'Thermometer', category: 'education', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'activity', displayName: 'Activity', category: 'education', usageContexts: ['column_templates', 'sites', 'xpages'] },

  // Food & Drink (15)
  { iconName: 'wine', displayName: 'Wine', category: 'food', usageContexts: ['sites', 'xpages'] },
  { iconName: 'beer', displayName: 'Beer', category: 'food', usageContexts: ['sites', 'xpages'] },
  { iconName: 'pizza', displayName: 'Pizza', category: 'food', usageContexts: ['sites', 'xpages'] },
  { iconName: 'cake', displayName: 'Cake', category: 'food', usageContexts: ['sites', 'xpages'] },
  { iconName: 'apple', displayName: 'Apple', category: 'food', usageContexts: ['sites', 'xpages'] },
  { iconName: 'cherry', displayName: 'Cherry', category: 'food', usageContexts: ['sites', 'xpages'] },
  { iconName: 'grape', displayName: 'Grape', category: 'food', usageContexts: ['sites', 'xpages'] },
  { iconName: 'ice-cream', displayName: 'Ice Cream', category: 'food', usageContexts: ['sites', 'xpages'] },
  { iconName: 'cookie', displayName: 'Cookie', category: 'food', usageContexts: ['sites', 'xpages'] },
  { iconName: 'utensils-crossed', displayName: 'Utensils Crossed', category: 'food', usageContexts: ['sites', 'xpages'] },
  { iconName: 'chef-hat', displayName: 'Chef Hat', category: 'food', usageContexts: ['sites', 'xpages'] },
  { iconName: 'restaurant', displayName: 'Restaurant', category: 'food', usageContexts: ['sites', 'xpages'] },

  // Weather & Nature (15)
  { iconName: 'cloud-rain', displayName: 'Cloud Rain', category: 'weather', usageContexts: ['sites', 'xpages'] },
  { iconName: 'cloud-snow', displayName: 'Cloud Snow', category: 'weather', usageContexts: ['sites', 'xpages'] },
  { iconName: 'cloud-lightning', displayName: 'Cloud Lightning', category: 'weather', usageContexts: ['sites', 'xpages'] },
  { iconName: 'rainbow', displayName: 'Rainbow', category: 'weather', usageContexts: ['sites', 'xpages'] },
  { iconName: 'umbrella', displayName: 'Umbrella', category: 'weather', usageContexts: ['sites', 'xpages'] },
  { iconName: 'wind', displayName: 'Wind', category: 'weather', usageContexts: ['sites', 'xpages'] },
  { iconName: 'tornado', displayName: 'Tornado', category: 'weather', usageContexts: ['sites', 'xpages'] },
  { iconName: 'volcano', displayName: 'Volcano', category: 'weather', usageContexts: ['sites', 'xpages'] },
  { iconName: 'flower-2', displayName: 'Flower 2', category: 'weather', usageContexts: ['sites', 'xpages'] },
  { iconName: 'leaf', displayName: 'Leaf', category: 'weather', usageContexts: ['sites', 'xpages'] },

  // Medical & Health (15)
  { iconName: 'heart-pulse', displayName: 'Heart Pulse', category: 'medical', usageContexts: ['sites', 'xpages'] },
  { iconName: 'pill', displayName: 'Pill', category: 'medical', usageContexts: ['sites', 'xpages'] },
  { iconName: 'stethoscope', displayName: 'Stethoscope', category: 'medical', usageContexts: ['sites', 'xpages'] },
  { iconName: 'bandage', displayName: 'Bandage', category: 'medical', usageContexts: ['sites', 'xpages'] },
  { iconName: 'cross', displayName: 'Cross', category: 'medical', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'brain', displayName: 'Brain', category: 'medical', usageContexts: ['sites', 'xpages'] },
  { iconName: 'ear', displayName: 'Ear', category: 'medical', usageContexts: ['sites', 'xpages'] },
  { iconName: 'hand', displayName: 'Hand', category: 'medical', usageContexts: ['sites', 'xpages'] },
  { iconName: 'footprints', displayName: 'Footprints', category: 'medical', usageContexts: ['sites', 'xpages'] },

  // Sports & Recreation (15)
  { iconName: 'football', displayName: 'Football', category: 'sports', usageContexts: ['sites', 'xpages'] },
  { iconName: 'basketball', displayName: 'Basketball', category: 'sports', usageContexts: ['sites', 'xpages'] },
  { iconName: 'tennis', displayName: 'Tennis', category: 'sports', usageContexts: ['sites', 'xpages'] },
  { iconName: 'golf', displayName: 'Golf', category: 'sports', usageContexts: ['sites', 'xpages'] },
  { iconName: 'baseball', displayName: 'Baseball', category: 'sports', usageContexts: ['sites', 'xpages'] },
  { iconName: 'dumbbell', displayName: 'Dumbbell', category: 'sports', usageContexts: ['sites', 'xpages'] },
  { iconName: 'music', displayName: 'Music', category: 'sports', usageContexts: ['column_templates', 'sites', 'xpages'] },
  { iconName: 'gamepad', displayName: 'Gamepad', category: 'sports', usageContexts: ['sites', 'xpages'] },
  { iconName: 'dice-1', displayName: 'Dice 1', category: 'sports', usageContexts: ['sites', 'xpages'] }
];

export const EXPANDED_ICON_CATEGORIES = [
  'all', 'shapes', 'arrows', 'actions', 'status', 'files', 'communication', 
  'technology', 'people', 'business', 'transport', 'home', 'tools', 
  'education', 'food', 'weather', 'medical', 'sports'
] as const;